version: '3.1'

services:
  node-app:
    container_name: nodeApp
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    # restart: always
    depends_on:
      - db
    ports:
      - 9090:9090
    volumes:
      - /code/spotify-clone/node-server/src:/code/src

  db:
    container_name: postgres
    image: postgres
    # restart: always
    environment:
      POSTGRES_PASSWORD: abc123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    # restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db-data: